### ISSUE TITLE
[Feature] Emote: /version (/v)

### ISSUE THREAD

**Issue by Newms34** [OpNop/GW2-Alliance-Chat#11]
Might be a good idea to have an emote that simply returns the current version (`/v`) if the user wants to make sure they're running the latest TACS version.

**Comment by OpNop** [comment]
already implemented https://github.com/OpNop/GW2-Alliance-Chat/pull/10#event-4306767304

**Comment by OpNop** [comment]
Also should note, the server has login to do a version check on connection and will tell the user to download the new version
https://github.com/OpNop/GW2-Alliance-Chat/blob/master/Chat%20Server/app.js#L424
